<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GameApp.Domain\GameApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.11" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\Identity\" />
    <Folder Include="Extensions\Review\" />
    <Folder Include="Services\Identity\" />
    <Folder Include="Services\Review\" />
    <Folder Include="Services\Token\" />
    <Folder Include="Services\UserProfile\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
