<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2fd8d818-fe61-4ee2-969d-324f8e090ffe</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.4.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameApp.Application\GameApp.Application.csproj" />
    <ProjectReference Include="..\GameApp.Infrastructure\GameApp.Infrastructure.csproj" />
    <ProjectReference Include="..\GameApp.Domain\GameApp.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Endpoints\Identity\" />
    <Folder Include="Endpoints\Review\" />
    <Folder Include="Extensions\Application\Identity\" />
    <Folder Include="Extensions\Application\Review\" />
  </ItemGroup>
</Project>